export const labels = {
  title: "Where in the world?",
  search: "Search for a country...",
  filter: "Filter by Region",
  all: "All",
  africa: "Africa",
  americas: "Americas",
  asia: "Asia",
  europe: "Europe",
  oceania: "Oceania",
  population: "Population",
  region: "Region",
  capital: "Capital",
  darkMode: "Dark Mode",
  lightMode: "Light Mode",
  error: "Oops! Something went wrong.",
  errorDescription: "An unexpected error has occurred. Please try again.",
  tryAgain: "Try Again",
};
