export const labels = {
  title: "Where in the world?",
  search: "Search for a country...",
  filter: "Filter by Region",
  all: "All",
  africa: "Africa",
  americas: "Americas",
  asia: "Asia",
  europe: "Europe",
  oceania: "Oceania",
  population: "Population",
  region: "Region",
  capital: "Capital",
  darkMode: "Dark Mode",
  lightMode: "Light Mode",
  error: "Oops! Something went wrong.",
  errorDescription: "An unexpected error has occurred. Please try again.",
  tryAgain: "Try Again",
  back: "Back",
  nativeName: "Native Name",
  topLevelDomain: "Top Level Domain",
  currencies: "Currencies",
  languages: "Languages",
  borderCountries: "Border Countries",
  subRegion: "Sub Region",
  none: "None",
  noInformation: "No information found.",
};
